#!/usr/bin/env ruby

require File.dirname(__FILE__) + "/../config/rubundler"
r = Rubundler.new
r.setup_env

begin
  require 'merb-core'
  Merb.start_environment(:adapter => 'runner', :environment => ENV['MERB_ENV'] || 'development')
  DataMapper.repository.adapter.query "SELECT 1"
rescue SystemExit => e
  if e.success?
    puts "OK, You can start Merb successfully!"
    exit 0
  else
    puts "Got a SystemExit which was unexpected: #{e.message}"
    puts e.backtrace
    exit 2
  end
rescue Exception => e
  puts "Got an exception: #{e.class}, #{e.message}"
  puts e.backtrace
  exit 1
end
