#!/usr/bin/env ruby

root = File.expand_path(File.dirname(__FILE__) + '/..')
ENV["GEM_HOME"] = root + '/gems'
ENV["GEM_PATH"] = root + '/gems'
gem_config = YAML.load_file(root + "/config/gems.yml")

begin
  require 'minigems'
rescue LoadError
  require 'rubygems'
end
require 'spec'

load 'spec'
